config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :groups, except: %i[update edit]
  resources :savings, except: %i[update edit]
  resources :users, except: %i[update edit]

  get '/savings/new/:group', to: 'savings#new'

  post '/access', to: 'access_control#signin'
  get '/access', to: 'access_control#logout'

  get '/mysavings', to: 'savings#index'
  get '/myexternal', to: 'savings#my_external'

  root 'application#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goupedsaving.rb
class Goupedsaving < ApplicationRecord
  belongs_to :group
  belongs_to :saving
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name, format: { with: /[a-zA-Z0-9]/ }

  has_many :groupedsavings
  has_many :savings, through: :groupedsavings
  belongs_to :creator, class_name: 'User'
  scope :ordered_by_name, -> { order(:name) }
end

app/models/groupedsaving.rb
class Groupedsaving < ApplicationRecord
  belongs_to :group
  belongs_to :saving
end

app/models/saving.rb
class Saving < ApplicationRecord
  validates :name, :amount, presence: true
  validates :name, format: { with: /[a-zA-Z0-9]/ }
  validates :amount, numericality: true

  belongs_to :author, class_name: 'User'
  has_many :groupedsavings, dependent: :destroy
  has_many :groups, through: :groupedsavings
  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  scope :stand_alone_savings, -> { where('savings.id NOT IN (?)', Groupedsaving.distinct.pluck(:saving_id)) }
  scope :total_amount, -> { sum(:amount) }
  scope :for_the_month, -> { where('extract(year from savings.created_at) = ? and extract(month from savings.created_at)= ?', Date.today.year, Date.today.month) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name, format: { with: /[a-zA-Z0-9]/ }

  has_many :savings, foreign_key: 'author_id', class_name: 'Saving'
  has_many :groups, foreign_key: 'creator_id', class_name: 'Group'
end

app/controllers/access_control_controller.rb
class AccessControlController < ApplicationController
  def signin
    valid_user = User.where(name: params[:user][:name])
    if valid_user.empty?
      flash.notice = "User doesn't exists"
      redirect_to users_path
    else
      session[:user_name] = params[:user][:name]
      session[:user_id] = valid_user[0].id
      session[:avatar] = valid_user[0].avatar_url
      flash.notice = "Welcome back #{session[:username]}"
      redirect_to "/users/#{session[:user_id]}"
    end
  end

  def logout
    session.destroy
    flash.notice = 'Logged out successfully'
    redirect_to users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    render 'layouts/main'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :check_login

  def index
    @user = User.find(session[:user_id])
    @groups = Group.ordered_by_name
  end

  def show
    @group_savings = @group.savings.includes(:groupedsavings, :groups, :author).ordered_by_most_recent
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
      else
        format.html { redirect_to new_group_path, alert: @group.errors.full_messages }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @group.destroy
        format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      else
        format.html { redirect_to groups_url, notice: "Group couldn't be destroyed." }
      end
    end
  end

  private

  def set_group
    @group = Group.includes(:creator).find(params[:id])
  end

  def group_params
    params.require(:group).permit(:creator_id, :name, :icon)
  end

  def check_login
    redirect_to root_path if session[:user_name].nil?
  end
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController
  before_action :set_saving, only: %i[show edit update destroy]
  before_action :check_login

  # GET /savings
  # GET /savings.json
  def my_external
    @user = User.includes(:savings, :groups).find(session[:user_id])
    @savings = @user.savings.includes(:groups, :author).stand_alone_savings.ordered_by_most_recent
    render 'index'
  end

  def index
    @user = User.includes(:savings, :groups).find(session[:user_id])
    @savings = @user.savings.includes(:groups, :author).ordered_by_most_recent
  end

  def show; end

  def new
    @saving = Saving.new
    @group = params[:group]
  end

  def create
    @saving = Saving.new(saving_params)
    respond_to do |format|
      if @saving.save
        Groupedsaving.create(saving_id: @saving.id, group_id: group_param[:group_id]) unless group_param[:group_id].to_i.zero?
        format.html { redirect_to savings_path, notice: 'Saving was successfully created.' }
      else
        format.html { redirect_to "/savings/new/#{group_param[:group_id]}", alert: @saving.errors.full_messages }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @saving.destroy
        format.html { redirect_to savings_url, notice: 'Saving was successfully deleted.' }
      else
        format.html { redirect_to savings_url, notice: "Saving couldn't be deleted." }
      end
    end
  end

  private

  def set_saving
    @saving = Saving.find(params[:id])
  end

  def saving_params
    params.require(:saving).permit(:author_id, :name, :amount)
  end

  def group_param
    params.require(:saving).permit(:group_id)
  end

  def check_login
    redirect_to root_path if session[:user_name].nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :check_login, except: %i[index new create show]

  def index
    @user = User.new
    render 'sign_in'
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_name] = @user.name
        session[:user_id] = @user.id
        session[:avatar] = @user.avatar_url
        format.html { redirect_to "/users/#{@user.id}", notice: 'User was successfully created.' }
      else
        format.html { redirect_to new_user_path, alert: 'User already exists' }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @user.destroy
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      else
        format.html { redirect_to users_url, notice: "User couldn't be destroyed." }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :avatar_url)
  end

  def check_login
    redirect_to root_path if session[:user_name].nil?
  end
end

app/helpers/access_control_helper.rb
module AccessControlHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_rendering
    render partial: 'layouts/navbar' unless session[:user_id].nil?
  end

  def information_rendering
    render partial: 'layouts/info' unless notice.nil? && alert.nil?
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def groups_rendering(grps)
    render partial: 'groupslist', locals: { groups: grps } unless grps.nil?
  end
end

app/helpers/savings_helper.rb
module SavingsHelper
  def get_group_icon(sav)
    if sav.groups.first.nil?
      sav.author.avatar_url
    else
      sav.groups.first.icon
    end
  end

  def savings_rendering(savs)
    render partial: 'layouts/savinglist', locals: { savings: savs } unless savs.nil?
  end

  def total_savings(savs)
    savs.total_amount
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_avatar.html.erb
<div class="selecting-avatar">
  <%= form.radio_button :icon, "https://www.bigideasfest.org/sites/default/files/imagecache/group_images_showcase/default-group.png", checked: true, class: 'radio-default' %>
  <div>
    <img class="avatar-img" src="https://www.kindpng.com/picc/m/417-4174897_transparent-tax-icon-png-blue-tax-icon-png.png" alt="avatar1">
    <br>
    <%= form.radio_button :icon, "https://www.kindpng.com/picc/m/417-4174897_transparent-tax-icon-png-blue-tax-icon-png.png" %>
  </div>
  <div>
    <img class="avatar-img" src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQFAQcX_Wd5qOVq73nHbO26nIeWX5cvNkglhA&usqp=CAU" alt="avatar2">
    <br>
    <%= form.radio_button :icon, "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQFAQcX_Wd5qOVq73nHbO26nIeWX5cvNkglhA&usqp=CAU" %>
  </div>
  <div>
    <img class="avatar-img" src="https://www.iconfinder.com/data/icons/planner-color/64/popcorn-movie-time-512.png" alt="avatar3">
    <br>
    <%= form.radio_button :icon, "https://www.iconfinder.com/data/icons/planner-color/64/popcorn-movie-time-512.png" %>
  </div>
  <div>
    <img class="avatar-img" src="https://b7.pngbarn.com/png/535/527/wireless-router-computer-icons-wi-fi-computer-network-wifi-router-png-clip-art.png" alt="avatar4">
    <br>
    <%= form.radio_button :icon, "https://b7.pngbarn.com/png/535/527/wireless-router-computer-icons-wi-fi-computer-network-wifi-router-png-clip-art.png" %>
  </div>
  <div>
    <img class="avatar-img" src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSu6aBagvPCPcbi4P5h0Ar6FLS6aZo15hp_-A&usqp=CAU" alt="avatar5">
    <br>
    <%= form.radio_button :icon, "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSu6aBagvPCPcbi4P5h0Ar6FLS6aZo15hp_-A&usqp=CAU" %>
  </div>
  <div>
    <img class="avatar-img" src="https://image.flaticon.com/icons/png/512/1466/1466668.png" alt="avatar6">
    <br>
    <%= form.radio_button :icon, "https://image.flaticon.com/icons/png/512/1466/1466668.png" %>
  </div>
  <div>
    <img class="avatar-img" src="https://icon-library.com/images/utilities-icon/utilities-icon-1.jpg" alt="avatar7">
    <br>
    <%= form.radio_button :icon, "https://icon-library.com/images/utilities-icon/utilities-icon-1.jpg" %>
  </div>
  <div>
    <img class="avatar-img" src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Circle-icons-car.svg/1024px-Circle-icons-car.svg.png" alt="avatar8">
    <br>
    <%= form.radio_button :icon, "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Circle-icons-car.svg/1024px-Circle-icons-car.svg.png" %>
  </div>
</div>

app/views/groups/_form.html.erb
<%= information_rendering %>
<br>
<br>
<div class="main-space">
<%= form_with(model: group, local: true) do |form| %>
  <%= form.hidden_field :creator_id, value: session[:user_id] %>

  <div class="field">
    <%= form.label :name, class: "text-label font-med-blue" %>
    <br>
    <%= form.text_field :name, class: "text-input" %>
  </div>
  <br>
  <div class="field">
    <%= render partial: 'avatar', locals: {form: form }%>
    <br>
    <%= form.label :avatar_url,value: "Select the group icon", class: "text-label font-med-blue" %><br>
  </div>
  <br>
  <div class="actions new-saving">
    <%= form.submit 'Create New Group', :class => "pseudo-button orange" %>
  </div>
<% end %>
</div>

app/views/groups/_form.thml.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :creator_id, value: session[:user_id] %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.text_field :icon %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_groupslist.html.erb
<% groups.each do |group| %>
  <%= link_to group do %></td>
    <div class="object-display">
      <img class="object-image" src=<%= group.icon %> alt="" />
      <div class="object-info group">
        <h3><%= group.name %></h3>
        <%= group.created_at.strftime('%e-%b-%Y') %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<%= link_to "/users/#{session[:user_id]}" do %>
  <span class="small-button back-button font-light-blue"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i></span>
<% end %>
<div class="banner">
  <h1><%= session[:user_name].capitalize%>'s Groups</h1>
</div>

<%= information_rendering %>
<br><br>

<div class="items-list">
  <%= groups_rendering(@groups) %>
</div>

<%= link_to new_group_path do %>
  <span class="pseudo-button green new-saving">New Group</span>
<% end %>

app/views/groups/new.html.erb
<%= link_to '/groups' do %>
  <span class="small-button back-button font-light-blue"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i></span>
<% end %>

<div class="banner">
  <h1 class="font-light-blue">Create New Group</h1>
</div>
<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<%= link_to '/groups' do %>
  <span class="small-button back-button font-light-blue"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i></span>
<% end %>
<div class="banner group-info">
  <img class="object-image" src=<%= @group.icon %> alt="" />
  <br><br>
  <h1>Group: <%= @group.name %></h1>
  <br>
  <h3>Created by: <%= @group.creator.name%></h3>
  <br>
  <h3>Created on: <%= @group.created_at.strftime('%e-%b-%Y')%></h3>
  <br>
  <%= link_to group_path(@group.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
    <span class="pseudo-button control-button red">Delete</span>
  <% end %>
</div>

<%= information_rendering %>
<br><br>

<h1 class="font-light-blue">Savings for this group</h1>

<div class="items-list">
  <%= render partial: "layouts/savinglist", locals: { savings: @group_savings } %>
</div>

<%= link_to "/savings/new/#{@group.id}" do %>
  <span class="pseudo-button green new-saving">New Saving</span>
<% end %>

app/views/layouts/_info.html.erb
<div class="information orange">
  <p class="font-dark-blue"><%= notice %></p>
  <p class="font-dark-blue"><%= alert %></p>   
</div>

app/views/layouts/_navbar.html.erb
<%= link_to '/access', method: 'delete' do %>
  <span class="small-button font-orange">Log Out</span>
<% end %>

app/views/layouts/_savinglist.html.erb
<% savings.each do |saving| %>
  <%= link_to saving do %></td>
  <div class="object-display">
    <img class="object-image" src=<%= get_group_icon(saving) %> alt="" />
    <div class="object-info">
      <h3><%= saving.name %></h3>
      Created by: <%= saving.author.name %><br>
      <%= saving.created_at.strftime('%e-%b-%Y') %>
    </div>
    <div class="object-amount">
      $<%= ActiveSupport::NumberHelper.number_to_delimited(saving.amount) %>
    </div>
  </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="icon" href="https://image.flaticon.com/icons/png/512/189/189093.png">
    <title>Save It</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> 
    <link href="https://fonts.googleapis.com/css2?family=Parisienne&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= navbar_rendering %>
    <%= yield %>
  </body>
</html>

app/views/layouts/main.html.erb
<%= information_rendering %>
<body class="container">
  <div class="welcome-view">
    <div class="main-title font-dark-blue">
      Save It
    </div>
    <div class="button-section">
      <%= link_to "/users" do%>
        <span class="pseudo-button green">Sign In</span></a>
      <% end %>
    </div>
    <div class="button-section">
      <%= link_to "/users/new" do%>
        <span class="pseudo-button dark-blue">Register</span></a>
      <% end %>
    </div>
  </div>
</body>

app/views/savings/_form.html.erb
<%= information_rendering %>
<br>
<br>
<div class="main-space">
<%= form_with(model: saving, local: true) do |form| %>
  <%= form.hidden_field :author_id, value: session[:user_id] %>
  <%= form.hidden_field :group_id, value: @group %>
  <div class="field">
    <%= form.label :name, value: 'Description', class: "text-label font-med-blue" %>
    <br>
    <%= form.text_field :name, class: "text-input" %>
  </div>
  <br>
  <div class="field">
    <%= form.label :amount, value: 'Amount', class: "text-label font-med-blue" %>
    <br>
    <%= form.number_field :amount, min: 0.1 , max: 100000000, step: 0.01, class: "text-input" %>
  </div>
  <br><br>
  <div class="actions new-saving">
    <%= form.submit 'Create Saving', :class => "pseudo-button orange"%>
  </div>
<% end %>
</div>

app/views/savings/edit.html.erb
<h1>Editing Saving</h1>

<%= render 'form', saving: @saving %>

<%= link_to 'Show', @saving %> |
<%= link_to 'Back', savings_path %>

app/views/savings/index.html.erb
<%= link_to "/users/#{session[:user_id]}" do %>
  <span class="small-button back-button font-light-blue"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i></span>
<% end %>
<div class="banner">
  <h1>All <%= session[:user_name]%>'s Savings</h1>
</div>

<%= information_rendering %>

<div class="object-display total-amount">
    <div class="object-info total">
      <h2>Grand total for savings:</h2>
    </div>
    <div class="object-amount total-result">
      <%= ActiveSupport::NumberHelper.number_to_currency(@savings.total_amount.round(2)) %>
    </div>
</div>
<div class="object-display total-amount">
    <div class="object-info total">
      <h2>Total savings for <%= Date.today.strftime('%B')%>:</h2>
    </div>
    <div class="object-amount total-result">
      <%= ActiveSupport::NumberHelper.number_to_currency(@savings.for_the_month.total_amount.round(2)) %>
    </div>
</div>
<br>
<div class="items-list">
  <%= savings_rendering(@savings) %>
</div>

<%= link_to '/savings/new/0' do %>
  <span class="pseudo-button green new-saving">New Saving</span>
<% end %>

app/views/savings/new.html.erb
<%= link_to savings_path do %>
  <span class="small-button back-button font-light-blue"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i></span>
<% end %>

<div class="banner">
  <h1 class="font-light-blue">New Saving</h1>
</div>

<%= render 'form', saving: @saving %>

app/views/savings/show.html.erb
<%= link_to savings_path do %>
  <span class="small-button back-button font-light-blue"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i></span>
<% end %>
<div class="banner group-info">
  <img class="object-image" src=<%= get_group_icon(@saving) %> alt="" />
  <br><br>
  <h1>Name: <%= @saving.name %></h1>
  <br>
  <h1>&#128184; : $<%= ActiveSupport::NumberHelper.number_to_delimited(@saving.amount) %></h1>
  <br>
  <h3>Created on: <%= @saving.created_at.strftime('%e-%b-%Y')%></h3>
  <br>
  <%= link_to saving_path(@saving.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
    <span class="pseudo-button control-button red">Delete</span>
  <% end %>
</div>

app/views/users/_avatar.html.erb
<div class="selecting-avatar">
  <%= form.radio_button :avatar_url, "https://d1u1amw606tzwl.cloudfront.net/assets/users/avatar-default-96007ee5610cdc5a9eed706ec0889aec2257a3937d0fbb747cf335f8915f09b2.png", checked: true, class: 'radio-default' %>
  <div>
    <img class="avatar-img" src="https://images.all-free-download.com/images/graphiclarge/snow_white_cartoon_character_6824931.jpg" alt="avatar1">
    <br>
    <%= form.radio_button :avatar_url, "https://images.all-free-download.com/images/graphiclarge/snow_white_cartoon_character_6824931.jpg" %>
  </div>
  <div>
    <img class="avatar-img" src="https://library.kissclipart.com/20181005/pe/kissclipart-gif-me-preocupas-clipart-sina-weibo-avatar-clip-ar-8505f646feab9d9f.png" alt="avatar2">
    <br>
    <%= form.radio_button :avatar_url, "https://library.kissclipart.com/20181005/pe/kissclipart-gif-me-preocupas-clipart-sina-weibo-avatar-clip-ar-8505f646feab9d9f.png" %>
  </div>
  <div>
    <img class="avatar-img" src="https://icons.iconarchive.com/icons/wikipedia/flags/512/UG-Uganda-Flag-icon.png" alt="avatar3">
    <br>
    <%= form.radio_button :avatar_url, "https://icons.iconarchive.com/icons/wikipedia/flags/512/UG-Uganda-Flag-icon.png" %>
  </div>
  <div>
    <img class="avatar-img" src="https://cdn.countryflags.com/thumbs/rwanda/flag-400.png" alt="avatar4">
    <br>
    <%= form.radio_button :avatar_url, "https://cdn.countryflags.com/thumbs/rwanda/flag-400.png" %>
  </div>
  <div>
    <img class="avatar-img" src="https://www.iconfinder.com/data/icons/animals-1-1/512/9-512.png" alt="avatar5">
    <br>
    <%= form.radio_button :avatar_url, "https://www.iconfinder.com/data/icons/animals-1-1/512/9-512.png" %>
  </div>
  <div>
    <img class="avatar-img" src="https://cdn.shopify.com/s/files/1/2123/8425/products/169070636-LRG_530x.jpg?v=1578675882" alt="avatar6">
    <br>
    <%= form.radio_button :avatar_url, "https://cdn.shopify.com/s/files/1/2123/8425/products/169070636-LRG_530x.jpg?v=1578675882" %>
  </div>
  <div>
    <img class="avatar-img" src="https://thumbs.dreamstime.com/b/estrellas-venezuela-arepa-venezuelan-typical-food-eight-stars-s-flag-162092128.jpg" alt="avatar7">
    <br>
    <%= form.radio_button :avatar_url, "https://thumbs.dreamstime.com/b/estrellas-venezuela-arepa-venezuelan-typical-food-eight-stars-s-flag-162092128.jpg" %>
  </div>
  <div>
    <img class="avatar-img" src="https://www.iconfinder.com/data/icons/america-asia-oceania-africa-3/100/Peru-512.png" alt="avatar8">
    <br>
    <%= form.radio_button :avatar_url, "https://www.iconfinder.com/data/icons/america-asia-oceania-africa-3/100/Peru-512.png" %>
  </div>
</div>

app/views/users/_form.html.erb
<%= information_rendering %>
<br>
<br>
<div class="user-form">
<%= form_with(model: user, local: true) do |form| %>
  <div class="field">
    <%= form.label :name, class: "text-label font-dark-blue" %><br>
    <%= form.text_field :name, class: "text-input" %>
  </div>
  <br><br>
  <div class="field">
    <%= render partial: 'avatar', locals: {form: form }%>
    <br>
    <%= form.label :avatar_url,value: "Select your avatar", class: "text-label font-med-blue" %><br>
  </div>
  <br>
  <br>
  <div class="actions new-saving">
    <%= form.submit 'Register', :class => "pseudo-button orange" %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Avatar url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.avatar_url %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= link_to root_path do %>
  <span class="small-button back-button font-light-blue"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i></span>
<% end %>

<div class="banner">
  <h1>Create New User</h1>
</div>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="profile">
  <img class="avatar" src=<%= @user.avatar_url %> />
  <br><br>
  <h1 class="user-name"><%= @user.name.capitalize %></h1>
  <br><br><br>
  <%= link_to '/mysavings' do %>
    <span class="pseudo-button light-blue">My Savings</span></a>
  <% end %>
  <br><br>
  <%= link_to '/myexternal' do %>
    <span class="pseudo-button orange">External Savings</span></a>
  <% end %>
  <br><br>
  <%= link_to '/groups' do %>
    <span class="pseudo-button green">My Groups</span></a>
  <% end %>
  <br><br>
</div>

app/views/users/sign_in.html.erb
<%= link_to '/' do %>
  <span class="small-button back-button font-light-blue"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i></span>
<% end %>
<div class="banner">
  <h1>Welcome!</h1>
</div>
<%= information_rendering %>
<br>
<br>
<div class="main-space">
<%= form_for(@user,  url: "/access", method: :post) do |form| %>
  <div class="field">
    <%= form.label :name, "Enter your name", class: "text-label font-dark-blue" %><br><br>
    <%= form.text_field :name, class: "text-input" %>
  </div>
  <br>
  <br>
  <div class="actions">
    <%= form.submit 'Sign In', :class => "pseudo-button green"%>
  </div>
<% end %>
</div>